# This is a basic workflow to help you get started with Actions

name: Github Action for JIRA with google sheet

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Running GIT test
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Installing Google APIs to Authenticate the GOOGLE API with TOKEN 
        run: npm install googleapis@39 --save
        
      - name: Installing Jira-connector for the JIRA Authentication
        run: npm install jira-connector

      # Runs a set of commands using the runners shell, Run a multi-line script
      - name: Running the actual script of Nodejs 
        run: |
          echo write_google_sheet.js file is getting executed..
          node write_google_sheet.js
          echo Google Sheet has been updated with ticket number Please check
